version: '2.1'
services:
  grouper-db:
    restart: always
    container_name: grouper-db
    build: ./src/docker/postgres
    volumes:
      - ./db-data:/tmp
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=grouper
      - PGDATA=/tmp
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  grouper-api-app:
    restart: on-failure
    build: ./src/docker/admin-api
    container_name: grouper-api-app
    expose:
      - "8080"
      - "8001"
    environment:
      - GROUPER_STORE_FILES_IN_BD=true 
      - GROUPER_POSTGRES_PASSWORD=password
      - GROUPER_POSTGRES_USERNAME=postgres
      - GROUPER_POSTGRES_SERVICE=jdbc:postgresql://grouper-db:5432/grouper
      - GROUPER_DEBUG="True"
      - GROUPER_IN_PRODUCTION="True"
    ports:
      - 8080:8080
      - 8001:8001
    depends_on:
       grouper-db:
          condition: service_healthy
  redis:
    image: redis
    container_name: grouper-redis
    ports:
      - "6379:6379"

volumes:
  db-data: {}
